### ISSUE TITLE
Blockclock mini hanged at "Hello" message

### ISSUE THREAD

**Issue by iamveritas** [Bayernatoor/blockclock_mining_stats#2]
this morning I found the blockclock mini just showing the "Hello" message, nothing else.
I powered it off and on and nothing changed.
how can I troubleshoot this?
thanks

**Comment by Bayernatoor** [comment]
Hey. Yep this is a known issue #1  that I'll try to fix this week. That being said you can just rerun the script and that should fix it. 

Also, I just noticed that there might be an issue with the API response that I am getting from Braiins. I'll take a look at that as well.

Let me know if you have any other issues :)

**Comment by iamveritas** [comment]
thank you for replying so quickly! <3
how I can re-run the script? where are instructions on how to do that?

**Comment by Bayernatoor** [comment]
> thank you for replying so quickly! <3 how I can re-run the script? where are instructions on how to do that?

Hey sorry, I just realized that this issue was opened on an old version of this tool, which I no longer maintain. I've since made a newer version of this tool written in rust which you can find here: https://github.com/Bayernatoor/braiins_clock if that interests you :) 

If you run into any issues, let me know! It's also a work in progress.
